### ISSUE TITLE
HCP database reporting should look at ingestedVolume rather than storageCapacityUsed

### ISSUE THREAD

**Issue by ahill-ersa** [eResearchSA/reporting-unified#32]
Since HCP has DPL-2, we need to use ingestedVolume rather than storageCapacityUsed for the RDS report.

FUSA0003	ersa-fusa-nida-productionarchive-fusa0003	8,000	2,122.48	HCP

Refer to spreedsheet for more info (June 2017)

**Comment by Li-ReDBox** [comment]
Move to [frontend repository](https://github.com/eResearchSA/reporting-frontend/issues/55) as it is where will change take place.
